import { useEffect, useMemo, useState } from 'react';

import { getConfig } from '@edx/frontend-platform';
import { sendPageEvent, sendTrackEvent } from '@edx/frontend-platform/analytics';
import { useIntl } from '@edx/frontend-platform/i18n';
import { Form, Spinner } from '@openedx/paragon';
import classNames from 'classnames';
import PropTypes from 'prop-types';
import { Helmet } from 'react-helmet';
import { Link } from 'react-router-dom';
import Skeleton from 'react-loading-skeleton';

import ConfigurableRegistrationForm from './components/ConfigurableRegistrationForm';
import RegistrationFailure from './components/RegistrationFailure';
import { useRegistration } from './data/apiHook';
import {
  FORM_SUBMISSION_ERROR,
  TPA_AUTHENTICATION_FAILURE,
} from './data/constants';
import {
  isFormValid, prepareRegistrationPayload,
} from './data/utils';
import messages from './messages';
import { EmailField, NameField, UsernameField } from './RegistrationFields';
import {
  InstitutionLogistration,
  PasswordField,
  RedirectLogistration,
  ThirdPartyAuthAlert,
} from '../common-components';
import { useThirdPartyAuthContext } from '../common-components/components/ThirdPartyAuthContext';
import { useThirdPartyAuthHook } from '../common-components/data/apiHook';
import EnterpriseSSO from '../common-components/EnterpriseSSO';
import ThirdPartyAuth from '../common-components/ThirdPartyAuth';
import {
  COMPLETE_STATE, DEFAULT_STATE, LOGIN_PAGE, PENDING_STATE, REGISTER_PAGE,
} from '../data/constants';
import {
  getAllPossibleQueryParams, getTpaHint, getTpaProvider, isHostAvailableInQueryParams, setCookie, updatePathWithQueryParams,
} from '../data/utils';
import { useRegisterContext } from './components/RegisterContext';

const RegistrationPage = (props) => {
  const { formatMessage } = useIntl();
  const [step, setStep] = useState(1);

  const {
    fieldDescriptions,
    optionalFields,
    thirdPartyAuthApiStatus,
    thirdPartyAuthContext,
    setThirdPartyAuthContextBegin,
    setThirdPartyAuthContextSuccess,
    setThirdPartyAuthContextFailure,
  } = useThirdPartyAuthContext();

  const {
    autoSubmitRegForm,
    currentProvider,
    finishAuthUrl,
    pipelineUserDetails,
    providers,
    secondaryProviders,
    errorMessage: thirdPartyAuthErrorMessage,
  } = thirdPartyAuthContext;

  const {
    clearRegistrationBackendError,
    registrationFormData,
    registrationResult,
    registrationError,
    setEmailSuggestionContext,
    updateRegistrationFormData,
    setRegistrationError,
    setRegistrationResult,
    backendValidations,
    setBackendCountryCode,
  } = useRegisterContext();

  const registrationEmbedded = isHostAvailableInQueryParams();
  const platformName = getConfig().SITE_NAME;
  const flags = {
    showConfigurableEdxFields: getConfig().SHOW_CONFIGURABLE_EDX_FIELDS,
    showConfigurableRegistrationFields: getConfig().ENABLE_DYNAMIC_REGISTRATION_FIELDS,
    showMarketingEmailOptInCheckbox: getConfig().MARKETING_EMAILS_OPT_IN,
    autoGeneratedUsernameEnabled: getConfig().ENABLE_AUTO_GENERATED_USERNAME,
  };
  const {
    handleInstitutionLogin,
    institutionLogin,
  } = props;

  const registrationMutation = useRegistration({
    onSuccess: (data) => {
      setRegistrationResult(data);
      setRegistrationError({});
    },
    onError: (errorData) => {
      setRegistrationError(errorData);
      // If error occurs, might need to stay on step 2 or show error
    },
  });

  const [userPipelineDataLoaded, setUserPipelineDataLoaded] = useState(false);
  const registrationErrorCode = registrationError?.errorCode;
  const submitState = registrationMutation.isPending ? PENDING_STATE : DEFAULT_STATE;
  const queryParams = useMemo(() => getAllPossibleQueryParams(), []);
  const tpaHint = useMemo(() => getTpaHint(), []);
  
  const [formFields, setFormFields] = useState({ ...registrationFormData.formFields });
  const [configurableFormFields, setConfigurableFormFields] = useState({ ...registrationFormData.configurableFormFields });
  const [errors, setErrors] = useState({ ...registrationFormData.errors });
  const [errorCode, setErrorCode] = useState({ type: '', count: 0 });
  const [formStartTime, setFormStartTime] = useState(null);
  const [temporaryErrors, setTemporaryErrors] = useState({ ...registrationFormData.errors });
  const { host } = queryParams;

  useEffect(() => {
    if (!userPipelineDataLoaded && thirdPartyAuthApiStatus === COMPLETE_STATE) {
      if (thirdPartyAuthErrorMessage) {
        setErrorCode(prevState => ({ type: TPA_AUTHENTICATION_FAILURE, count: prevState.count + 1 }));
      }
      if (pipelineUserDetails && Object.keys(pipelineUserDetails).length !== 0) {
        const { name = '', username = '', email = '' } = pipelineUserDetails;
        setFormFields(prevState => ({ ...prevState, name, username, email }));
        setUserPipelineDataLoaded(true);
      }
    }
  }, [thirdPartyAuthApiStatus, thirdPartyAuthErrorMessage, pipelineUserDetails, userPipelineDataLoaded]);

  const params = { ...queryParams, is_register_page: true };
  if (tpaHint) { params.tpa_hint = tpaHint; }

  const { data, isSuccess, error } = useThirdPartyAuthHook(REGISTER_PAGE, params);
  
  useEffect(() => {
    if (!formStartTime) {
      sendPageEvent('login_and_registration', 'register');
      setThirdPartyAuthContextBegin();
      setFormStartTime(Date.now());
    }
    if (formStartTime) {
      if (isSuccess && data) {
        setThirdPartyAuthContextSuccess(data.fieldDescriptions, data.optionalFields, data.thirdPartyAuthContext);
        setBackendCountryCode(data.thirdPartyAuthContext.countryCode);
      }
      if (error) { setThirdPartyAuthContextFailure(); }
    }
  }, [formStartTime, isSuccess, data, error]);

  useEffect(() => {
    if (backendValidations) {
      setErrors(prevErrors => ({ ...prevErrors, ...backendValidations }));
    }
  }, [backendValidations]);

  useEffect(() => {
    if (registrationErrorCode) {
      setErrorCode(prevState => ({ type: registrationErrorCode, count: prevState.count + 1 }));
    }
  }, [registrationErrorCode]);

  useEffect(() => {
    if (registrationResult.success) {
      sendTrackEvent('edx.bi.user.account.registered.client', {});
      setCookie(getConfig().USER_RETENTION_COOKIE_NAME, true);
    }
  }, [registrationResult]);

  const handleOnChange = (event) => {
    const { name } = event.target;
    const value = event.target.type === 'checkbox' ? event.target.checked : event.target.value;
    setErrors(prevErrors => ({ ...prevErrors, [name]: '' }));
    const newFormFields = { ...formFields, [name]: value };
    setFormFields(newFormFields);
    updateRegistrationFormData({ formFields: newFormFields, errors, configurableFormFields });
  };

  const handleErrorChange = (fieldName, errorMessage) => {
    setErrors(prevErrors => ({ ...prevErrors, [fieldName]: errorMessage }));
  };

  const handleNextStep = (e) => {
    e.preventDefault();
    // Validate Step 1 fields
    const step1Fields = ['name', 'email', 'username', 'password'];
    let step1Valid = true;
    const newErrors = { ...errors };

    if (!formFields.name) { newErrors.name = 'Name is required'; step1Valid = false; }
    if (!formFields.email) { newErrors.email = 'Email is required'; step1Valid = false; }
    if (!flags.autoGeneratedUsernameEnabled && !formFields.username) {
      newErrors.username = 'Username is required'; step1Valid = false;
    }
    if (!currentProvider && !formFields.password) {
      newErrors.password = 'Password is required'; step1Valid = false;
    }

    if (step1Valid) {
      setStep(2);
    } else {
      setErrors(newErrors);
    }
  };

  const handleSubmit = (e) => {
    e.preventDefault();
    const totalRegistrationTime = (Date.now() - formStartTime) / 1000;
    let payload = { ...formFields };

    const { isValid, fieldErrors, emailSuggestion } = isFormValid(
      payload,
      errors,
      configurableFormFields,
      fieldDescriptions,
      formatMessage,
    );
    setErrors({ ...fieldErrors });
    setEmailSuggestionContext(emailSuggestion.suggestion, emailSuggestion.type);

    if (!isValid) {
      setErrorCode(prevState => ({ type: FORM_SUBMISSION_ERROR, count: prevState.count + 1 }));
      return;
    }

    payload = prepareRegistrationPayload(
      payload,
      configurableFormFields,
      flags.showMarketingEmailOptInCheckbox,
      totalRegistrationTime,
      queryParams
    );
    registrationMutation.mutate(payload);
  };

  const renderForm = () => {
    if (institutionLogin) {
      return (
        <InstitutionLogistration
          secondaryProviders={secondaryProviders}
          headingTitle={formatMessage(messages['register.institution.login.page.title'])}
        />
      );
    }
    return (
      <div className="kku-register-container">
        <Helmet>
          <title>{formatMessage(messages['register.page.title'], { siteName: getConfig().SITE_NAME })}</title>
        </Helmet>
        <RedirectLogistration
          host={host}
          authenticatedUser={registrationResult.authenticatedUser}
          success={registrationResult.success}
          redirectUrl={registrationResult.redirectUrl}
          finishAuthUrl={finishAuthUrl}
          optionalFields={optionalFields}
          registrationEmbedded={registrationEmbedded}
          redirectToProgressiveProfilingPage={
            getConfig().ENABLE_PROGRESSIVE_PROFILING_ON_AUTHN && !!Object.keys(optionalFields.fields).length
          }
        />

        <h2 className="kku-title text-center">Create Account</h2>
        <p className="kku-subtitle text-center">Create your account to start learning</p>

        <div className="kku-step-indicator">
          <div className={classNames('step-item', { active: step >= 1 })}>
            <div className="step-circle">1</div>
            <div className="step-text">Account Details</div>
          </div>
          <div className={classNames('step-item', { active: step >= 2 })}>
            <div className="step-circle">2</div>
            <div className="step-text">Additional Info</div>
          </div>
        </div>

        <RegistrationFailure
          errorCode={errorCode.type}
          failureCount={errorCode.count}
          context={{ provider: currentProvider, errorMessage: thirdPartyAuthErrorMessage }}
        />

        <div className="kku-registration-container">
          <Form id="registration-form" name="registration-form">
            {step === 1 ? (
            <>
              {!currentProvider && (
                <>
                  <p className="kku-social-label">Register with</p>
                  <div className="kku-social-container">
                    <ThirdPartyAuth
                      currentProvider={currentProvider}
                      providers={providers}
                      secondaryProviders={secondaryProviders}
                      handleInstitutionLogin={handleInstitutionLogin}
                      thirdPartyAuthApiStatus={thirdPartyAuthApiStatus}
                    />
                  </div>
                </>
              )}
              {!currentProvider && (
                <div className="kku-divider">
                  <span>or register with email</span>
                </div>
              )}

              <div className="kku-field-grid">
                <NameField
                  name="name"
                  value={formFields.name}
                  handleChange={handleOnChange}
                  handleErrorChange={handleErrorChange}
                  errorMessage={errors.name}
                  floatingLabel={formatMessage(messages['registration.fullname.label'])}
                />
                <EmailField
                  name="email"
                  value={formFields.email}
                  handleChange={handleOnChange}
                  handleErrorChange={handleErrorChange}
                  errorMessage={errors.email}
                  floatingLabel={formatMessage(messages['registration.email.label'])}
                />
                {!flags.autoGeneratedUsernameEnabled && (
                  <UsernameField
                    name="username"
                    value={formFields.username}
                    handleChange={handleOnChange}
                    handleErrorChange={handleErrorChange}
                    errorMessage={errors.username}
                    floatingLabel={formatMessage(messages['registration.username.label'])}
                  />
                )}
                {!currentProvider && (
                  <PasswordField
                    name="password"
                    value={formFields.password}
                    handleChange={handleOnChange}
                    handleErrorChange={handleErrorChange}
                    errorMessage={errors.password}
                    floatingLabel={formatMessage(messages['registration.password.label'])}
                  />
                )}
              </div>
              <button type="button" className="kku-gradient-btn" onClick={handleNextStep}>
                Next -> Additional Information
              </button>
            </>
          ) : (
            <>
              <ConfigurableRegistrationForm
                email={formFields.email}
                fieldErrors={errors}
                formFields={configurableFormFields}
                setFieldErrors={setErrors}
                setFormFields={setConfigurableFormFields}
                fieldDescriptions={fieldDescriptions}
              />
              <div className="kku-btn-group">
                <button type="button" className="kku-back-btn" onClick={() => setStep(1)}>
                  Back
                </button>
                <button type="submit" className="kku-gradient-btn" onClick={handleSubmit} disabled={submitState === PENDING_STATE}>
                  {submitState === PENDING_STATE ? 'Creating...' : 'Create Account'}
                </button>
              </div>
            </>
          )}
        </Form>
        </div>

        <div className="kku-footer-signup">
          Already have an account? 
          <Link to={updatePathWithQueryParams(LOGIN_PAGE)} className="signup-link">
            Sign In
          </Link>
        </div>
      </div>
    );
  };

  if (tpaHint && thirdPartyAuthApiStatus === PENDING_STATE) {
    return <Skeleton height={36} />;
  }

  return renderForm();
};

RegistrationPage.propTypes = {
  institutionLogin: PropTypes.bool,
  handleInstitutionLogin: PropTypes.func,
};

export default RegistrationPage;
